# Generated by Django 3.0.5 on 2020-04-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsmodel_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='language',
            field=models.CharField(choices=[('az', 'Az'), ('rus', 'Rus'), ('en', 'En')], default='az', max_length=20),
        ),
    ]
