# Generated by Django 3.0.5 on 2020-04-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200409_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='publised',
            new_name='published',
        ),
    ]
