# Generated by Django 3.0.5 on 2020-04-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('complaint', 'Complaint'), ('proposal', 'Proposal'), ('application', 'Application')], default='aapplication', max_length=20)),
                ('department', models.CharField(max_length=250)),
                ('subject', models.CharField(choices=[('complaint', 'Complaint'), ('proposal', 'Proposal'), ('application', 'Application')], default='aapplication', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
