# Generated by Django 3.0.5 on 2020-04-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('language', models.CharField(choices=[('az', 'Az'), ('rus', 'Rus'), ('en', 'En')], default='az', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('role', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('language', models.CharField(choices=[('az', 'Az'), ('rus', 'Rus'), ('en', 'En')], default='az', max_length=20)),
            ],
        ),
    ]
